fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\User
  registration:
    form:
      type: App\Form\Type\RegistrationFormType
  from_email:
    address: "lukaphptesting@gmail.com"
    sender_name: "undefined2019;"
  service:
    mailer: fos_user.mailer.twig_swift